# Generated by Django 4.2.6 on 2023-10-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iha_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iha",
            name="details",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
