# Generated by Django 4.2.6 on 2023-10-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iha_app", "0003_kiralama"),
    ]

    operations = [
        migrations.AddField(
            model_name="kiralama",
            name="iha_kiralanan",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="iha_app.iha"
            ),
        ),
        migrations.AlterField(
            model_name="kiralama",
            name="kullanici_ismi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
